# Generated by Django 4.0.4 on 2022-10-04 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_remove_newuser_firstname_alter_newuser_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newuser',
            old_name='eduaction',
            new_name='education',
        ),
    ]
